### ISSUE TITLE
Mutation field wrapped `query`

### ISSUE THREAD

**Issue by whlsxl** [Skitionek/gql-generator-node#1]
https://github.com/Skitionek/gql-generator-node/blob/master/src/index.js#L156

```
result[kind][type] = generateQuery({ field, kind: description, parentName: description, depthLimit, dedupe });
```

`generateQuery` should add `kind`

**Comment by MehdiSaffar** [comment]
I was using the released version, noticed the same bug and was about to fork and fix it, but then saw this post. Anyway you could publish this fixed version to npm? Published version is from April 20 2020 while the Fix was done on October 8 2021

**Comment by Skitionek** [comment]
Sure 👍

**Comment by Skitionek** [comment]
@MehdiSaffar thank you for the comment - I believed that I had some pipeline in place for that 😅

BTW Please feel free also to open issues/feature requests I am glad this project is gaining some interest and I am eager to give it some attention.

**Comment by MehdiSaffar** [comment]
@Skitionek Yes I saw the CI github action you had there, not sure why it didn't trigger in this case!
In our project's test suite I use a lot of gql strings and it was tedious to "copy" from the schema file to test util files. This saved me a ton of time so thank you a lot!
